@startuml
left to right direction

title Diagrama Lógico - Sistema de Aluguel de Automóveis

actor "Cliente" as cliente
actor "Banco" as banco
actor "Empresa" as empresa


rectangle Sistema {
    usecase "Introduzir Pedido" as UC1
    usecase "Modificar Pedido" as UC2
    usecase "Consultar Pedido" as UC3
    usecase "Cancelar Pedido" as UC4
    usecase "Mandar Pedido para Avaliação" as UC9

    usecase "Modificar Pedido" as UC5
    usecase "Avaliar Pedido" as UC7
    usecase "Conceder Crédito" as UC8
    usecase "Criar Contrato" as UC10


    cliente -- UC1

    cliente -- UC2
    cliente -- UC3
    cliente -- UC4
    cliente -- UC9
    
    banco -- UC8

    empresa -- UC5
    empresa -- UC7

    UC7 .> UC10 :<<include>>

    empresa <|-- banco

}


@enduml