@startuml
left to right direction

' Definição dos componentes
component "Navegador Web" as navegador
component "Spring Boot" as spring {
    component "Controller" as controller
    component "Service" as service
    component "Repository" as repository
}

database "Banco de Dados" as banco_dados

' Conexões entre os componentes
navegador --> spring : HTTP/HTTPS
controller --> service 
service --> repository 
repository --> banco_dados : TCP/IP

@enduml