@startuml
skinparam linetype ortho

package "AluguelDeCarrosAPI" {
    
    package "Controller" {
        [UsuarioController]
        [ContratoController]
        [VeiculoController]
        [PedidoController]
        [AgenteController]
    }

    package "Service" {
        [UsuarioService]
        [ContratoService]
        [VeiculoService]
        [PedidoService]
        [AgenteService]
    }

    package "Repository" {
        [UsuarioRepository]
        [ContratoRepository]
        [VeiculoRepository]
        [PedidoRepository]
        [AgenteRepository]
    }

    package "Models" {
        [UsuarioModel]
        [ContratoModel]
        [VeiculoModel]
        [PedidoModel]
        [AgenteModel]
    }

    package "Utils" {
        [HttpResponseUtil]
    }
}

package "Database" {
    [DatabaseManager]
}

package "Frontend" {

    package "Libraries" {
        [React]
        [Lodash]
        [Axios]
    }

    package "Frameworks" {
        [NextJS]
    }

    package "BuildTools" {
        [Webpack]
        [Babel]
    }

    package "PackageManagers" {
        [NPM]
        [Yarn]
    }

    package "StylesAndUI" {
        [TailwindCSS]
        [Material-UI]
    }

    package "ReactComponents" {
        [UserComponent]
        [ContractComponent]
        [VehicleComponent]
        [OrderComponent]
        [AgentComponent]
    }
}

' Dependências
Controller --> Service
Service --> Repository
Repository --> Models
Service --> Utils
Repository --> Database
Database --> DatabaseManager

Frontend --> Controller
ReactComponents --> Libraries
ReactComponents --> Frameworks
ReactComponents --> StylesAndUI
ReactComponents --> BuildTools
ReactComponents --> PackageManagers

@enduml
